
server :
  port : 9696
spring:
  shell:
    interactive:
      enabled: true
  debug: true

cloud:
  aws:
    credentials:
      accessKey: <Your Acess key Cloudfare R2>
      secretKey: <Your Secret key Cloudfare R2>
    s3:
      region: auto
      endpoint: <Your Cloudfare Storage uri >
      path-style-access: true
